// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NewsService.Infrastructure.Data;

#nullable disable

namespace NewsService.Infrastructure.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20260602130000_AddNewsEnrichmentAttempt")]
    partial class AddNewsEnrichmentAttempt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewsService.Domain.Entities.NewsArticle", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<string>("Source").HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("source");
                b.Property<string>("SourceUrl").HasMaxLength(1024).HasColumnType("character varying(1024)").HasColumnName("source_url");
                b.Property<string>("Title").HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("title");
                b.Property<string>("Summary").HasColumnType("text").HasColumnName("summary");
                b.Property<string>("ImageUrl").HasMaxLength(1024).HasColumnType("character varying(1024)").HasColumnName("image_url");
                b.Property<string>("Content").HasColumnType("text").HasColumnName("content");
                b.Property<DateTime>("PublishedAt").HasColumnType("timestamp with time zone").HasColumnName("published_at");
                b.Property<string[]>("Tags").HasColumnType("text[]").HasColumnName("tags");
                b.Property<DateTime>("IngestedAt").HasColumnType("timestamp with time zone").HasColumnName("ingested_at");
                b.Property<DateTime?>("EnrichmentAttemptedAt").HasColumnType("timestamp with time zone").HasColumnName("enrichment_attempted_at");

                b.HasKey("Id").HasName("pk_news_articles");
                b.HasIndex("PublishedAt").HasDatabaseName("ix_news_articles_published_at");
                b.HasIndex("SourceUrl").IsUnique().HasDatabaseName("ux_news_articles_source_url");
                b.HasIndex("Tags").HasDatabaseName("ix_news_articles_tags_gin").HasAnnotation("Npgsql:IndexMethod", "gin");
                b.ToTable("news_articles", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
