$f = 'c:\Users\zzz20\ModelLine\microservice_admin\src\app\download\page.tsx'
$lines = Get-Content $f

# Lines 302-330 (0-indexed 301-329) contain the broken TF row body.
# Replace them with correctly-indented content.

$fixed = [System.Collections.Generic.List[string]]::new()
$fixed.Add("                  {st === 'done' && m?.rows === 0       && <AlertTriangle className=`"w-3.5 h-3.5 text-yellow-500`" />}")
$fixed.Add("                  {st === 'error'  && <XCircle           className=`"w-3.5 h-3.5 text-destructive`" />}")
$fixed.Add("                </div>")
$fixed.Add("                <span className={cn(")
$fixed.Add("                  'text-xs font-mono w-9 shrink-0',")
$fixed.Add("                  st === 'pending' && 'text-muted-foreground',")
$fixed.Add("                  st === 'running' && 'text-foreground',")
$fixed.Add("                  st === 'done' && (m?.rows ?? 1) > 0 && 'text-foreground',")
$fixed.Add("                  st === 'done' && m?.rows === 0 && 'text-yellow-500',")
$fixed.Add("                  st === 'error'  && 'text-destructive',")
$fixed.Add("                )}>")
$fixed.Add("                  {tf}")
$fixed.Add("                </span>")
$fixed.Add("                <div className=`"flex flex-1 items-center gap-2 min-w-0`">")
$fixed.Add("                  {st === 'running' && m?.stage && (")
$fixed.Add("                    <span className=`"text-[10px] text-primary tabular-nums truncate`">")
$fixed.Add("                      {m.stage}{m.pct != null ? ` `${m.pct}%` : ''}")
$fixed.Add("                    </span>")
$fixed.Add("                  )}")
$fixed.Add("                  {elapsed !== undefined && st !== 'running' && (")
$fixed.Add("                    <span className=`"text-[10px] text-muted-foreground tabular-nums`">")
$fixed.Add("                      {fmtDur(elapsed)}")
$fixed.Add("                    </span>")
$fixed.Add("                  )}")
$fixed.Add("                  {m?.rows !== undefined && (")
$fixed.Add("                    <span className={cn(")
$fixed.Add("                      'text-[10px] tabular-nums',")
$fixed.Add("                      m.rows === 0 ? 'text-yellow-500' : 'text-muted-foreground',")
$fixed.Add("                    )}>")
$fixed.Add("                      {m.rows.toLocaleString()} $([char]0x441)$([char]0x442)$([char]0x440)$([char]0x43E)$([char]0x43A)")
$fixed.Add("                    </span>")
$fixed.Add("                  )}")
$fixed.Add("                  {st === 'error' && m?.error && (")
$fixed.Add("                    <span className=`"text-[10px] text-destructive truncate min-w-0`">")
$fixed.Add("                      {m.error.length > 40 ? m.error.slice(0, 40) + '$([char]0x2026)' : m.error}")
$fixed.Add("                    </span>")
$fixed.Add("                  )}")
$fixed.Add("                </div>")
$fixed.Add("              </div>")
$fixed.Add("              {st === 'running' && m?.pct != null && (")
$fixed.Add("                <Progress value={m.pct} className=`"h-0.5 ml-5 w-full`" />")
$fixed.Add("              )}")
$fixed.Add("            </div>")

$newLines = [System.Collections.Generic.List[string]]::new()
$newLines.AddRange($lines[0..300])
$newLines.AddRange($fixed)
$newLines.AddRange($lines[329..($lines.Length - 1)])

[System.IO.File]::WriteAllLines($f, $newLines, [System.Text.UTF8Encoding]::new($false))
Write-Host "Done. Lines: before=$($lines.Length) after=$($newLines.Count)"
