// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SocialService.Infrastructure.Data;

#nullable disable

namespace SocialService.Infrastructure.Migrations
{
    [DbContext(typeof(SocialDbContext))]
    partial class SocialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SocialService.Domain.Entities.Favorite", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<string>("Symbol").HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("symbol");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");

                b.HasKey("UserId", "Symbol").HasName("pk_favorites");
                b.HasIndex("Symbol").HasDatabaseName("ix_favorites_symbol");
                b.ToTable("favorites", (string)null);
            });

            modelBuilder.Entity("SocialService.Domain.Entities.Comment", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<string>("TargetType").HasMaxLength(16).HasColumnType("character varying(16)").HasColumnName("target_type");
                b.Property<string>("TargetId").HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("target_id");
                b.Property<Guid?>("ParentId").HasColumnType("uuid").HasColumnName("parent_id");
                b.Property<string>("Body").HasMaxLength(4000).HasColumnType("character varying(4000)").HasColumnName("body");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.Property<DateTime?>("DeletedAt").HasColumnType("timestamp with time zone").HasColumnName("deleted_at");

                b.HasKey("Id").HasName("pk_comments");
                b.HasIndex("ParentId").HasDatabaseName("ix_comments_parent_id");
                b.HasIndex("TargetType", "TargetId", "CreatedAt").HasDatabaseName("ix_comments_target_type_target_id_created_at");
                b.ToTable("comments", (string)null);
            });

            modelBuilder.Entity("SocialService.Domain.Entities.CommentLike", b =>
            {
                b.Property<Guid>("CommentId").HasColumnType("uuid").HasColumnName("comment_id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");

                b.HasKey("CommentId", "UserId").HasName("pk_comment_likes");
                b.HasIndex("CommentId").HasDatabaseName("ix_comment_likes_comment_id");
                b.ToTable("comment_likes", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
