// <auto-generated />
using System;
using AccountService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountService.Infrastructure.Migrations;

[DbContext(typeof(AccountDbContext))]
partial class AccountDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("AccountService.Domain.Entities.AuditLoginEvent", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd()
                .HasColumnType("uuid").HasColumnName("id");
            b.Property<string>("EventType").IsRequired()
                .HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("event_type");
            b.Property<string>("IpAddress")
                .HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("ip_address");
            b.Property<string>("Metadata")
                .HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("metadata");
            b.Property<DateTimeOffset>("OccurredAt")
                .HasColumnType("timestamp with time zone").HasColumnName("occurred_at");
            b.Property<string>("UserAgent")
                .HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("user_agent");
            b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
            b.HasKey("Id").HasName("pk_audit_login_events");
            b.HasIndex("UserId").HasDatabaseName("ix_audit_login_events_user_id");
            b.ToTable("audit_login_events");
        });

        modelBuilder.Entity("AccountService.Domain.Entities.ExchangeApiKey", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
            b.Property<string>("Exchange").IsRequired()
                .HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("exchange");
            b.Property<string>("Label").IsRequired()
                .HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("label");
            b.Property<string>("ApiKeyEnc").IsRequired()
                .HasMaxLength(1024).HasColumnType("character varying(1024)").HasColumnName("api_key_enc");
            b.Property<string>("ApiSecretEnc").IsRequired()
                .HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("api_secret_enc");
            b.Property<string>("ApiKeyMasked").IsRequired()
                .HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("api_key_masked");
            b.Property<bool>("CanRead").HasColumnType("boolean").HasColumnName("can_read");
            b.Property<bool>("CanTrade").HasColumnType("boolean").HasColumnName("can_trade");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
            b.Property<DateTime?>("LastUsedAt").HasColumnType("timestamp with time zone").HasColumnName("last_used_at");
            b.Property<string>("Status").IsRequired()
                .HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
            b.Property<string>("LastValidationError")
                .HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("last_validation_error");
            b.Property<DateTime?>("LastValidatedAt").HasColumnType("timestamp with time zone").HasColumnName("last_validated_at");
            b.HasKey("Id").HasName("pk_exchange_api_keys");
            b.HasIndex("UserId", "Exchange").HasDatabaseName("ix_exchange_api_keys_user_id_exchange");
            b.ToTable("exchange_api_keys");
        });

        modelBuilder.Entity("AccountService.Domain.Entities.ExchangeMetadata", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
            b.Property<string>("Exchange").IsRequired()
                .HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("exchange");
            b.Property<string>("Symbol").IsRequired()
                .HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("symbol");
            b.Property<string>("Category").IsRequired()
                .HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("category");
            b.Property<decimal?>("MakerFeeBps").HasColumnType("numeric(18,6)").HasColumnName("maker_fee_bps");
            b.Property<decimal?>("TakerFeeBps").HasColumnType("numeric(18,6)").HasColumnName("taker_fee_bps");
            b.Property<decimal?>("MinNotional").HasColumnType("numeric(28,8)").HasColumnName("min_notional");
            b.Property<decimal?>("MaxLeverage").HasColumnType("numeric(8,2)").HasColumnName("max_leverage");
            b.Property<string>("RawJson").IsRequired().HasColumnType("jsonb").HasColumnName("raw_json");
            b.Property<DateTime>("CapturedAt").HasColumnType("timestamp with time zone").HasColumnName("captured_at");
            b.HasKey("Id").HasName("pk_exchange_metadata");
            b.HasIndex("Exchange", "Symbol", "Category").IsUnique().HasDatabaseName("ix_exchange_metadata_exchange_symbol_category");
            b.ToTable("exchange_metadata");
        });

        modelBuilder.Entity("AccountService.Domain.Entities.RefreshToken", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd()
                .HasColumnType("uuid").HasColumnName("id");
            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone").HasColumnName("created_at");
            b.Property<string>("DeviceId")
                .HasMaxLength(128).HasColumnType("character varying(128)").HasColumnName("device_id");
            b.Property<DateTimeOffset>("ExpiresAt")
                .HasColumnType("timestamp with time zone").HasColumnName("expires_at");
            b.Property<string>("IpAddress")
                .HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("ip_address");
            b.Property<DateTimeOffset?>("RevokedAt")
                .HasColumnType("timestamp with time zone").HasColumnName("revoked_at");
            b.Property<string>("TokenHash").IsRequired()
                .HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("token_hash");
            b.Property<string>("UserAgent")
                .HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("user_agent");
            b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
            b.HasKey("Id").HasName("pk_refresh_tokens");
            b.HasIndex("TokenHash").IsUnique().HasDatabaseName("ix_refresh_tokens_token_hash");
            b.HasIndex("UserId").HasDatabaseName("ix_refresh_tokens_user_id");
            b.ToTable("refresh_tokens");
        });

        modelBuilder.Entity("AccountService.Domain.Entities.Role", b =>
        {
            b.Property<int>("Id").HasColumnType("integer").HasColumnName("id");
            b.Property<string>("Code").IsRequired()
                .HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("code");
            b.Property<string>("Name").IsRequired()
                .HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("name");
            b.HasKey("Id").HasName("pk_roles");
            b.HasIndex("Code").IsUnique().HasDatabaseName("ix_roles_code");
            b.ToTable("roles");
            b.HasData(
                new { Id = 0, Code = "guest", Name = "Guest" },
                new { Id = 1, Code = "user", Name = "User" },
                new { Id = 2, Code = "admin", Name = "Administrator" });
        });

        modelBuilder.Entity("AccountService.Domain.Entities.User", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd()
                .HasColumnType("uuid").HasColumnName("id");
            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone").HasColumnName("created_at");
            b.Property<string>("Email").IsRequired()
                .HasMaxLength(320).HasColumnType("character varying(320)").HasColumnName("email");
            b.Property<string>("PasswordHash").IsRequired()
                .HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("password_hash");
            b.Property<string>("Status").IsRequired()
                .HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("status");
            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone").HasColumnName("updated_at");
            b.Property<string>("Username").IsRequired()
                .HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("username");
            b.HasKey("Id").HasName("pk_users");
            b.HasIndex("Email").IsUnique().HasDatabaseName("ix_users_email");
            b.HasIndex("Username").IsUnique().HasDatabaseName("ix_users_username");
            b.ToTable("users");
        });

        modelBuilder.Entity("AccountService.Domain.Entities.UserRole", b =>
        {
            b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
            b.Property<int>("RoleId").HasColumnType("integer").HasColumnName("role_id");
            b.HasKey("UserId", "RoleId").HasName("pk_user_roles");
            b.HasIndex("RoleId").HasDatabaseName("ix_user_roles_role_id");
            b.ToTable("user_roles");
        });

        modelBuilder.Entity("AccountService.Domain.Entities.UserSettings", b =>
        {
            b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone").HasColumnName("created_at");
            b.Property<string>("Locale").IsRequired()
                .HasMaxLength(10).HasColumnType("character varying(10)").HasColumnName("locale");
            b.Property<bool>("NotificationsEnabled")
                .HasColumnType("boolean").HasColumnName("notifications_enabled");
            b.Property<string>("Theme").IsRequired()
                .HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("theme");
            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone").HasColumnName("updated_at");
            b.HasKey("UserId").HasName("pk_user_settings");
            b.ToTable("user_settings");
        });

        // Relationships
        modelBuilder.Entity("AccountService.Domain.Entities.AuditLoginEvent", b =>
        {
            b.HasOne("AccountService.Domain.Entities.User", "User")
                .WithMany("AuditLoginEvents")
                .HasForeignKey("UserId")
                .HasConstraintName("fk_audit_login_events_users_user_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("AccountService.Domain.Entities.RefreshToken", b =>
        {
            b.HasOne("AccountService.Domain.Entities.User", "User")
                .WithMany("RefreshTokens")
                .HasForeignKey("UserId")
                .HasConstraintName("fk_refresh_tokens_users_user_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("AccountService.Domain.Entities.UserRole", b =>
        {
            b.HasOne("AccountService.Domain.Entities.Role", "Role")
                .WithMany("UserRoles")
                .HasForeignKey("RoleId")
                .HasConstraintName("fk_user_roles_roles_role_id")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.HasOne("AccountService.Domain.Entities.User", "User")
                .WithMany("UserRoles")
                .HasForeignKey("UserId")
                .HasConstraintName("fk_user_roles_users_user_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("AccountService.Domain.Entities.UserSettings", b =>
        {
            b.HasOne("AccountService.Domain.Entities.User", "User")
                .WithOne("Settings")
                .HasForeignKey("AccountService.Domain.Entities.UserSettings", "UserId")
                .HasConstraintName("fk_user_settings_users_user_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
