"""Пакет обучения и оценки CatBoost-модели для прогнозирования target_return_1."""
from __future__ import annotations

from .cache import (
    CACHE_DIR,
    cache_stats,
    clear_cache,
    load_cached_dataset,
    save_cached_dataset,
)
from .config import (
    DEFAULT_PARAM_VALUES,
    DEVICES,
    EARLY_STOPPING_ROUNDS,
    GPU_RAM_PART,
    MODELS_DIR,
    PARAM_GRID,
    RANDOM_SEED,
    TARGET_COLUMN,
    TARGET_COLUMN_PREFIX,
    TASK_TYPE,
    TRAIN_FRACTION,
    VERBOSE_TRAIN,
    annualize_factor,
    expand_param_grid,
    timeframe_to_ms,
)
from .loader import list_target_candidates, load_training_data, load_training_data_from_rows
from .mlflow_utils import log_session_to_mlflow, mlflow_available
from .pdf_report import generate_session_pdf, generate_session_pdf_bytes
from .metrics import compute_direction_metrics, compute_metrics, compute_trading_metrics
from .report import (
    compute_shap_values,
    delete_registry_version,
    load_grid_best_params,
    load_grid_session_result,
    load_optuna_best_params,
    load_optuna_session_result,
    load_registry,
    load_session_result,
    load_shap_summary,
    plot_actual_vs_predicted,
    plot_cumulative_pnl,
    plot_feature_importance,
    register_model_version,
    save_grid_best_params,
    save_grid_results,
    save_optuna_best_params,
    save_optuna_results,
    save_predictions_json,
    save_results_json,
    save_session_result,
    save_shap_summary,
)
from .train import (
    compute_overfitting_diagnostics,
    grid_search_cv,
    optuna_search_cv,
    save_model,
    train_final_model,
    walk_forward_split,
)

__all__ = [
    "CACHE_DIR",
    "DEFAULT_PARAM_VALUES",
    "DEVICES",
    "EARLY_STOPPING_ROUNDS",
    "GPU_RAM_PART",
    "MODELS_DIR",
    "PARAM_GRID",
    "RANDOM_SEED",
    "TARGET_COLUMN",
    "TARGET_COLUMN_PREFIX",
    "TASK_TYPE",
    "TRAIN_FRACTION",
    "VERBOSE_TRAIN",
    "annualize_factor",
    "cache_stats",
    "timeframe_to_ms",
    "clear_cache",
    "expand_param_grid",
    "generate_session_pdf",
    "generate_session_pdf_bytes",
    "list_target_candidates",
    "load_cached_dataset",
    "log_session_to_mlflow",
    "mlflow_available",
    "load_training_data",
    "save_cached_dataset",
    "compute_metrics",
    "compute_direction_metrics",
    "compute_trading_metrics",
    "compute_shap_values",
    "delete_registry_version",
    "load_grid_best_params",
    "load_grid_session_result",
    "load_optuna_best_params",
    "load_optuna_session_result",
    "load_registry",
    "load_session_result",
    "load_shap_summary",
    "plot_actual_vs_predicted",
    "plot_cumulative_pnl",
    "plot_feature_importance",
    "register_model_version",
    "save_grid_best_params",
    "save_grid_results",
    "save_optuna_best_params",
    "save_optuna_results",
    "save_predictions_json",
    "save_results_json",
    "save_session_result",
    "save_shap_summary",
    "compute_overfitting_diagnostics",
    "grid_search_cv",
    "optuna_search_cv",
    "save_model",
    "train_final_model",
    "walk_forward_split",
]
