// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NotificationService.Infrastructure.Data;

#nullable disable

namespace NotificationService.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260603000003_AddPriceAlerts")]
    partial class AddPriceAlerts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<string>("Kind").HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("kind");
                b.Property<string>("Title").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("title");
                b.Property<string>("Body").HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("body");
                b.Property<string>("Deeplink").HasMaxLength(1024).HasColumnType("character varying(1024)").HasColumnName("deeplink");
                b.Property<string>("PayloadJson").HasColumnType("jsonb").HasColumnName("payload_json");
                b.Property<string>("DedupKey").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("dedup_key");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime?>("ReadAt").HasColumnType("timestamp with time zone").HasColumnName("read_at");

                b.HasKey("Id").HasName("pk_notifications");
                b.HasIndex("UserId", "CreatedAt").HasDatabaseName("ix_notifications_user_id_created_at");
                b.HasIndex("UserId", "ReadAt").HasDatabaseName("ix_notifications_user_id_read_at");
                b.HasIndex("UserId", "Kind", "DedupKey").HasDatabaseName("ix_notifications_dedup");
                b.ToTable("notifications", (string)null);
            });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationSettings", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<bool>("EnableReply").HasColumnType("boolean").HasColumnName("enable_reply");
                b.Property<bool>("EnableNews").HasColumnType("boolean").HasColumnName("enable_news");
                b.Property<bool>("EnablePrice").HasColumnType("boolean").HasColumnName("enable_price");
                b.Property<decimal>("PriceThresholdPct").HasColumnType("numeric(8,4)").HasColumnName("price_threshold_pct");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");

                b.HasKey("UserId").HasName("pk_notification_settings");
                b.ToTable("notification_settings", (string)null);
            });

            modelBuilder.Entity("NotificationService.Domain.Entities.PushSubscription", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<string>("Endpoint").HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("endpoint");
                b.Property<string>("P256dh").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("p256dh");
                b.Property<string>("Auth").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("auth");
                b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("user_agent");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime>("LastSeenAt").HasColumnType("timestamp with time zone").HasColumnName("last_seen_at");
                b.Property<int>("FailureCount").HasColumnType("integer").HasColumnName("failure_count");

                b.HasKey("Id").HasName("pk_push_subscriptions");
                b.HasIndex("Endpoint").IsUnique().HasDatabaseName("ux_push_subscriptions_endpoint");
                b.HasIndex("UserId").HasDatabaseName("ix_push_subscriptions_user_id");
                b.ToTable("push_subscriptions", (string)null);
            });

            modelBuilder.Entity("NotificationService.Domain.Entities.PriceAlert", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<string>("Symbol").HasMaxLength(32).HasColumnType("character varying(32)").HasColumnName("symbol");
                b.Property<string>("Condition").HasMaxLength(8).HasColumnType("character varying(8)").HasColumnName("condition");
                b.Property<decimal>("TargetPrice").HasColumnType("numeric").HasColumnName("target_price");
                b.Property<bool>("IsEnabled").HasColumnType("boolean").HasColumnName("is_enabled");
                b.Property<bool>("IsArmed").HasColumnType("boolean").HasColumnName("is_armed");
                b.Property<DateTime?>("LastTriggeredAt").HasColumnType("timestamp with time zone").HasColumnName("last_triggered_at");
                b.Property<decimal?>("LastObservedPrice").HasColumnType("numeric").HasColumnName("last_observed_price");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");

                b.HasKey("Id").HasName("pk_price_alerts");
                b.HasIndex("UserId").HasDatabaseName("ix_price_alerts_user_id");
                b.HasIndex("IsEnabled").HasDatabaseName("ix_price_alerts_is_enabled");
                b.ToTable("price_alerts", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
